name: Build
on:
  push:
    branches:
    - develop

jobs:
  buildAndDeploy:
    name: Build and Deploy Blog

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - run: yarn
    - run: yarn build

    - name: Notify Me On Failure
      if: failure() || cancelled()
      uses: swinton/httpie.action@master
      env:
        FREE_ID_KEY: ${{ secrets.FREE_ID_KEY }}
        FREE_USER: ${{ secrets.FREE_USER }}
      with:
        args: GET smsapi.free-mobile.fr/sendmsg user==$FREE_USER pass==$FREE_ID_KEY
          "msg=='Blog deployed !'"
